### PR TITLE
Display version in footer

### PR DESCRIPTION
**Pull request by vilhelmprytz**
This is an example of how it looks.

Example

### CODE REVIEW

**Review by Linux123123 — CHANGES_REQUESTED** [review]
And we would use semantic versioning or just the commit hash?

Otherwise looks good.

**Comment by vilhelmprytz** [comment]
> And we would use semantic versioning or just the commit hash?
> 
> Otherwise looks good.

I think it's overkill to semantically version this project :slightly_smiling_face:

**Comment by Linux123123** [comment]
So the version hash is basically to see if it is updated, correct?

**Comment by vilhelmprytz** [comment]
More or less, yes. I think it's a nice feature to have, just to avoid confusion.

**Review by Linux123123 — APPROVED** [review]

**Pull request merged**
