### PR TITLE
Create an update command for the bot

### PR DESCRIPTION
**Pull request by sinmineryt**
Many people have been asking how to update wings or the panel, so i've decided adding an !update command with some triggers based on the messages sent in the discord server.
I have tested out the changes in a private discord server.

### CODE REVIEW

**Comment by vilhelmprytz** [comment]
Sorry, I just reformated using Prettier. Can you resolve conflicts or close this PR and send it again? I'll merge the contribution right away :slightly_smiling_face:

**Comment by sinmineryt** [comment]
Did a mistake here.

**Comment by vilhelmprytz** [comment]
Another option is to close this one and open a new one, but with the changes you included :slightly_smiling_face:

**Comment by sinmineryt** [comment]
Am I dumb now?

**Comment by sinmineryt** [comment]
I'll just close and create another one.

**Comment by sinmineryt** [comment]
Recreated the PR: #9

**Pull request closed without merging**
