### PR TITLE
Add dependabot for automatic dependency updates

### PR DESCRIPTION
**Pull request by sinmineryt**
This will add dependabot to this repository, like requested in #11

### CODE REVIEW

**Comment by vilhelmprytz** [comment]
Doesn't dependabot do this automatically or is this config required?

**Comment by Linux123123** [comment]
Yes, this config is more or less required, but you can also enable it in the repo settings. I think that we can add it.

**Comment by vilhelmprytz** [comment]
image

I think dependabot checks for security alerts and whatnot. If I am correct, dependabot is also able to send dependency upgrade PRs regardless of security vulnerabilities?

**Comment by sinmineryt** [comment]
Dependabot automatically updates the dependencies when there is a new release regardless if there is a security vulnerability or not. An example is in my fork, it created pull requests there!

> Doesn't dependabot do this automatically or is this config required?
That config is required for the automatic updating.

**Review by vilhelmprytz — APPROVED** [review]
LGTM

**Pull request merged**
